<?php
/**
 * @file
 * Code for the OS2intra base feature.
 */

include_once 'os2intra_base.features.inc';

function os2intra_base_views_pre_render(&$view) {
   if($view->name == "os2intra_group_term_activity" && !empty($view->result)) {
       // Only show results which the user is allowed to.
       $group_memberships = og_get_groups_by_user();
       if(!empty($group_memberships['node'])) {
	       foreach($view->result as $i => $row) {
	           if (!in_array((int) $row->node_og_membership_nid, $group_memberships['node'])) {
	           	unset($view->result[$i]);
	           }
	       }
       }
   }
}


function mytools_form_alter(&$form, $form_state, $form_id) {
 error_log($form_id);
}
